#!/bin/sh
set -eu

# Arguments
DATABASE=$1

# Handle OS X support
SED_REGEXP="-r"
if [ "$(uname)" = "Darwin" ]; then
    SED_REGEXP="-E"
fi

# Export the database
mkdir -p "$DATABASE"
mysqldump --no-data --skip-comments --skip-add-drop-table --skip-set-charset -u root "$DATABASE" \
  | grep -v -e '^$' \
  | grep -v "\!40101 SET" \
  | grep -v "\!50003 SET" \
  | sed $SED_REGEXP -e 's|/\*!50017.*\*/ ||' \
  > "$DATABASE/latest.sql"
